// One catalog for server validation and the simulated route shown on every screen.
export const countries = [
  { code: "MX", name: "México", city: "Ciudad de México", airport: "Aeropuerto de Ciudad de México" },
  { code: "US", name: "Estados Unidos", city: "Nueva York", airport: "Aeropuerto JFK, Nueva York" },
  { code: "CA", name: "Canadá", city: "Toronto", airport: "Aeropuerto Toronto Pearson" },
  { code: "BR", name: "Brasil", city: "São Paulo", airport: "Aeropuerto de Guarulhos" },
  { code: "CO", name: "Colombia", city: "Bogotá", airport: "Aeropuerto El Dorado, Bogotá" },
  { code: "AR", name: "Argentina", city: "Buenos Aires", airport: "Aeropuerto de Ezeiza" },
  { code: "CL", name: "Chile", city: "Santiago", airport: "Aeropuerto de Santiago" },
  { code: "PE", name: "Perú", city: "Lima", airport: "Aeropuerto Jorge Chávez, Lima" },
  { code: "EC", name: "Ecuador", city: "Quito", airport: "Aeropuerto de Quito" },
  { code: "CR", name: "Costa Rica", city: "San José", airport: "Aeropuerto Juan Santamaría" },
  { code: "PA", name: "Panamá", city: "Ciudad de Panamá", airport: "Aeropuerto de Tocumen" },
  { code: "ES", name: "España", city: "Madrid", airport: "Aeropuerto Madrid-Barajas" },
  { code: "FR", name: "Francia", city: "París", airport: "Aeropuerto Charles de Gaulle, París" },
  { code: "DE", name: "Alemania", city: "Fráncfort", airport: "Aeropuerto de Fráncfort" },
  { code: "GB", name: "Reino Unido", city: "Londres", airport: "Aeropuerto Heathrow, Londres" },
  { code: "IT", name: "Italia", city: "Milán", airport: "Aeropuerto de Malpensa, Milán" },
  { code: "PT", name: "Portugal", city: "Lisboa", airport: "Aeropuerto de Lisboa" },
  { code: "NL", name: "Países Bajos", city: "Ámsterdam", airport: "Aeropuerto de Schiphol" },
  { code: "CH", name: "Suiza", city: "Zúrich", airport: "Aeropuerto de Zúrich" },
  { code: "SE", name: "Suecia", city: "Estocolmo", airport: "Aeropuerto de Arlanda" },
  { code: "TR", name: "Turquía", city: "Estambul", airport: "Aeropuerto de Estambul" },
  { code: "AE", name: "Emiratos Árabes Unidos", city: "Dubái", airport: "Aeropuerto de Dubái" },
  { code: "IN", name: "India", city: "Nueva Delhi", airport: "Aeropuerto Indira Gandhi" },
  { code: "CN", name: "China", city: "Shanghái", airport: "Aeropuerto de Pudong, Shanghái" },
  { code: "HK", name: "Hong Kong", city: "Hong Kong", airport: "Aeropuerto de Hong Kong" },
  { code: "JP", name: "Japón", city: "Tokio", airport: "Aeropuerto de Narita, Tokio" },
  { code: "KR", name: "Corea del Sur", city: "Seúl", airport: "Aeropuerto de Incheon" },
  { code: "SG", name: "Singapur", city: "Singapur", airport: "Aeropuerto de Changi" },
  { code: "TH", name: "Tailandia", city: "Bangkok", airport: "Aeropuerto de Suvarnabhumi" },
  { code: "AU", name: "Australia", city: "Sídney", airport: "Aeropuerto de Sídney" },
  { code: "NZ", name: "Nueva Zelanda", city: "Auckland", airport: "Aeropuerto de Auckland" },
  { code: "ZA", name: "Sudáfrica", city: "Johannesburgo", airport: "Aeropuerto O. R. Tambo" },
] as const

export const countryCodes = new Set<string>(countries.map(({ code }) => code))
