import { FormEvent, ReactNode, useEffect, useState } from "react";
import { apiFetch, supabase } from "./lib/supabase";
import { createBrowserRouter, Link, NavLink, Outlet, RouterProvider, useNavigate, useParams } from "react-router";

type IconName = "box" | "scan" | "search" | "clock" | "user" | "chevron" | "arrow" | "camera" | "check" | "filter" | "pin" | "eye";
function Icon({ name, className = "" }: { name: IconName; className?: string }) {
  const paths: Record<IconName, ReactNode> = {
    box: <><path d="M3 7.5 12 3l9 4.5v9L12 21l-9-4.5v-9Z"/><path d="m3 7.5 9 4.5 9-4.5M12 12v9"/></>,
    scan: <><path d="M4 8V5a1 1 0 0 1 1-1h3M16 4h3a1 1 0 0 1 1 1v3M20 16v3a1 1 0 0 1-1 1h-3M8 20H5a1 1 0 0 1-1-1v-3"/><path d="M8 12h8M9 9v6M12 9v6M15 9v6"/></>,
    search: <><circle cx="10.8" cy="10.8" r="5.8"/><path d="m16 16 4 4"/></>,
    clock: <><circle cx="12" cy="12" r="8.5"/><path d="M12 7v5l3.5 2"/></>,
    user: <><circle cx="12" cy="8" r="3"/><path d="M5 20c.7-3.2 3-5 7-5s6.3 1.8 7 5"/></>,
    chevron: <path d="m9 18 6-6-6-6"/>, arrow: <><path d="M5 12h14"/><path d="m13 6 6 6-6 6"/></>,
    camera: <><path d="M4 8h3l1.4-2h7.2L17 8h3v11H4V8Z"/><circle cx="12" cy="13" r="3.2"/></>,
    check: <path d="m5 12 4 4L19 6"/>, filter: <><path d="M4 6h16M7 12h10M10 18h4"/></>,
    pin: <><path d="M12 21s6-5.6 6-11a6 6 0 1 0-12 0c0 5.4 6 11 6 11Z"/><circle cx="12" cy="10" r="2"/></>, eye: <><path d="M3 12s3-5 9-5 9 5 9 5-3 5-9 5-9-5-9-5Z"/><circle cx="12" cy="12" r="2"/></>
  };
  return <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.85" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>;
}

function Auth() {
  const nav = useNavigate();
  return <main className="auth-shell"><section className="auth-top"><div className="brand-mark"><Icon name="box"/></div><span className="brand-name">milenio<span>express</span></span><div className="auth-orbit orbit-one"/><div className="auth-orbit orbit-two"/></section><section className="auth-card role-card"><div className="eyebrow">MÓVIL DE LOGÍSTICA</div><h1>¿Cómo quieres continuar?</h1><p>Elige el acceso que corresponde a tu operación.</p><div className="role-actions"><button className="role-button client-role" onClick={()=>nav("/inicio")}><span className="role-icon"><Icon name="user"/></span><span><strong>Iniciar como cliente</strong><small>Consulta el estado de tus envíos</small></span><Icon name="chevron"/></button><button className="role-button driver-role" onClick={()=>nav("/inicio")}><span className="role-icon"><Icon name="box"/></span><span><strong>Acceso de repartidor</strong><small>Gestiona entregas y comprobantes</small></span><Icon name="chevron"/></button></div><p className="role-note">Podrás cambiar de sección desde el menú inferior.</p></section></main>;
}

function Shell() { return <div className="app-shell"><header className="app-header"><Link to="/inicio" className="mini-brand"><div><Icon name="box"/></div><b>milenio<span>express</span></b></Link><button className="avatar">AM</button></header><Outlet/><nav className="bottom-nav"><NavLink to="/inicio"><Icon name="search"/><span>Rastrear</span></NavLink><NavLink to="/historial"><Icon name="clock"/><span>Historial</span></NavLink><NavLink to="/perfil"><Icon name="user"/><span>Perfil</span></NavLink></nav></div> }
const recent = [{id:"ME-8472-1903", place:"Monterrey, NL", state:"En reparto", tone:"blue"},{id:"ME-1294-8816", place:"Guadalajara, JAL", state:"En tránsito", tone:"violet"},{id:"ME-5573-2081", place:"Ciudad de México", state:"Entregado", tone:"green"}];
function PackageCard({item}:{item: typeof recent[number]}) { return <Link to="/envio/ME-8472-1903" className="package-card"><div className={`package-icon ${item.tone}`}><Icon name="box"/></div><div className="package-copy"><small>{item.id}</small><strong>{item.place}</strong><span className={`status ${item.tone}`}>{item.state}</span></div><Icon name="chevron" className="chevron"/></Link> }
function Home(){ const nav=useNavigate(); const [code,setCode]=useState(""); const [items,setItems]=useState<any[]>([]); const [error,setError]=useState(""); useEffect(()=>{apiFetch("/shipments").then(setItems).catch(e=>setError(e.message))},[]); return <main className="screen home-screen"><div className="greeting"><div><div className="eyebrow">OPERACIONES · HOY</div><h1>Hola, Andrea.</h1></div><span className="online-dot">En línea</span></div><form className="tracking-search" onSubmit={(e)=>{e.preventDefault();nav("/envio/"+(code||items[0]?.id||"ME-8472-1903"))}}><Icon name="search"/><input value={code} onChange={e=>setCode(e.target.value)} placeholder="Ingresa tu número de guía"/><button type="submit"><Icon name="arrow"/></button></form><section className="section"><div className="section-title"><div><div className="eyebrow">ACTIVIDAD</div><h2>Paquetes recientes</h2></div><Link to="/historial">Ver todo</Link></div>{error?<p className="form-error">{error}</p>:<div className="package-list">{items.map(x=><PackageCard key={x.id} item={x}/>)}</div>}</section></main> }
function Shipment(){ const nav=useNavigate(); const { id = "" }=useParams(); const [shipment,setShipment]=useState<any>(); const [error,setError]=useState(""); useEffect(()=>{apiFetch(`/shipments/${id}`).then(setShipment).catch(e=>setError(e.message))},[id]); if(error)return <main className="screen"><button onClick={()=>nav(-1)} className="round-button">←</button><p className="form-error">{error}</p></main>; if(!shipment)return <main className="screen"><p>Consultando envío…</p></main>; const activeIndex=shipment.events.findIndex((x:any)=>x.title===shipment.state); return <main className="screen"><div className="back-row"><button onClick={()=>nav(-1)} className="round-button">←</button><div><div className="eyebrow">DETALLE DE ENVÍO</div><h2>{shipment.id}</h2></div></div><section className="destination-card"><div className="pin-wrap"><Icon name="pin"/></div><div><small>DESTINO</small><strong>{shipment.address}</strong><span>{shipment.place}</span></div></section><section className="section timeline-section"><div className="section-title"><div><div className="eyebrow">SEGUIMIENTO</div><h2>Estado del envío</h2></div><span className={`status ${shipment.tone}`}>{shipment.state}</span></div><div className="timeline">{shipment.events.map((step:any,i:number)=><div className={`timeline-item ${i<=activeIndex?"active":""}`} key={step.title}><div className="track"><span>{i<activeIndex?<Icon name="check"/>:i+1}</span>{i<shipment.events.length-1&&<i/>}</div><div><strong>{step.title}</strong><p>{step.desc}</p><small>{step.time}</small></div></div>)}</div></section>{shipment.state!=="Entregado"&&<Link className="primary-button deliver-button" to={`/entrega/${shipment.id}`}>Confirmar entrega <Icon name="arrow"/></Link>}</main> }
function History(){ const [filter,setFilter]=useState("Todos"); const [items,setItems]=useState<any[]>([]); const [error,setError]=useState(""); const options=["Todos","En tránsito","En reparto","Entregado"]; useEffect(()=>{apiFetch("/shipments").then(setItems).catch(e=>setError(e.message))},[]); const list=filter==="Todos"?items:items.filter(x=>x.state===filter); return <main className="screen"><div className="eyebrow">CONSULTA OPERATIVA</div><h1>Historial</h1><div className="filters"><div className="filter-chips">{options.map(x=><button key={x} onClick={()=>setFilter(x)} className={filter===x?"active":""}>{x}</button>)}</div></div><div className="history-count"><span>{list.length} envíos encontrados</span><Icon name="filter"/></div>{error?<p className="form-error">{error}</p>:<div className="package-list">{list.map(x=><PackageCard key={x.id} item={x}/>)}</div>}</main> }
function Delivery(){ const [signed,setSigned]=useState(false);const [photo,setPhoto]=useState(false);const [name,setName]=useState("Mariana Cárdenas");const [saving,setSaving]=useState(false);const [error,setError]=useState("");const nav=useNavigate(); const { id="" }=useParams(); const complete=async()=>{setSaving(true);setError("");try{await apiFetch(`/shipments/${id}/deliver`,{method:"POST",body:JSON.stringify({signedBy:name,photoAttached:photo})});nav("/historial")}catch(e:any){setError(e.message)}finally{setSaving(false)}};return <main className="screen delivery"><div className="back-row"><button onClick={()=>nav(-1)} className="round-button">←</button><div><div className="eyebrow">CIERRE DE ENVÍO</div><h2>Confirmar entrega</h2></div></div><div className="delivery-recipient"><div className="person-icon"><Icon name="user"/></div><div><small>RECIBE</small><strong>{name}</strong><span>{id}</span></div></div><section className="proof-block"><div className="block-label"><span>Firma digital</span><small>{signed?"Registrada":"Requerida"}</small></div><button onClick={()=>setSigned(!signed)} className={`signature-pad ${signed?"signed":""}`}>{signed?<><em>{name}</em><Icon name="check"/></>:<><span>Confirmar firma de {name}</span><b>✎</b></>}</button></section><section className="proof-block"><div className="block-label"><span>Fotografía de prueba</span><small>{photo?"Adjunta":"Requerida"}</small></div><button onClick={()=>setPhoto(!photo)} className={`photo-proof ${photo?"done":""}`}>{photo?<><Icon name="check"/><strong>Fotografía adjunta</strong><span>Lista para guardar</span></>:<><Icon name="camera"/><strong>Registrar fotografía</strong><span>Fachada, recepción o paquete</span></>}</button></section>{error&&<p className="form-error">{error}</p>}<button disabled={!signed||!photo||saving} onClick={complete} className="primary-button confirm-button">{saving?"Guardando…":"Completar entrega"} <Icon name="check"/></button></main> }
function Profile(){const nav=useNavigate();const logout=async()=>{await supabase.auth.signOut();nav("/")};return <main className="screen"><div className="eyebrow">CUENTA</div><h1>Perfil</h1><div className="profile-card"><div className="profile-avatar">AM</div><strong>Andrea Mendoza</strong><span>Operaciones · Monterrey</span></div><button onClick={logout} className="secondary-button" style={{marginTop:20}}>Cerrar sesión</button></main>}
const router=createBrowserRouter([{path:"/",Component:Auth},{Component:Shell,children:[{path:"/inicio",Component:Home},{path:"/envio/:id",Component:Shipment},{path:"/historial",Component:History},{path:"/entrega/:id",Component:Delivery},{path:"/perfil",Component:Profile}]}]);
export default function App(){return <RouterProvider router={router}/>}
